namespace BAExamApp.DataAccess.Interfaces.Repositories.Candidate;
public interface ICandidateBranchRepository : IAsyncRepository, IAsyncQueryableRepository<CandidateCandidateBranch>, IAsyncFindableRepository<CandidateCandidateBranch>, IAsyncInsertableRepository<CandidateCandidateBranch>, IAsyncUpdateableRepository<CandidateCandidateBranch>, IAsyncDeleteableRepository<CandidateCandidateBranch>
{
}
